# Generated by Django 6.0.4 on 2026-04-28 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_debt_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('operator', models.CharField(choices=[('orange_ml', 'Orange Mali'), ('malitel', 'Malitel')], max_length=10, verbose_name='Opérateur')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé (FCFA)')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Crédit téléphonique',
                'verbose_name_plural': 'Crédits téléphoniques',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
