# Generated by Django 6.0.4 on 2026-05-09 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_merge_20260508_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='card_size',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='interface_layout',
        ),
        migrations.AddField(
            model_name='product',
            name='pack_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour calculer automatiquement (prix × quantité paquet).', max_digits=10, null=True, verbose_name='Prix du paquet (FCFA)'),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Ex : 12 si un paquet contient 12 pièces. Mettre 1 si pas de paquet.', max_digits=10, verbose_name='Quantité par paquet'),
        ),
        migrations.AddField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, help_text='Ex: vente enregistrée le lendemain, notée sur papier.', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(default=datetime.date.today, help_text='Vous pouvez changer cette date pour enregistrer une vente passée.', verbose_name='Date de vente'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale_mode',
            field=models.CharField(choices=[('detail', 'Détail'), ('paquet', 'Paquet')], default='detail', max_length=10, verbose_name='Mode de vente'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='due_date',
            field=models.DateField(verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogramme'), ('l', 'Litre'), ('pièce', 'Pièce'), ('sachet', 'Sachet'), ('boîte', 'Boîte')], default='pièce', max_length=20, verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='background_image',
            field=models.FileField(blank=True, upload_to='backgrounds/', verbose_name='Image de fond facture'),
        ),
    ]
