# Generated by Django 6.0.4 on 2026-05-09 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_sale_options_remove_storesettings_card_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='storesettings',
            name='invoice_watermark',
            field=models.FileField(blank=True, upload_to='watermarks/', verbose_name='Filigrane facture'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='due_date',
            field=models.DateField(verbose_name='Date d’échéance'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix du paquet (FCFA)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_size',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Taille paquet'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de vente'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='background_image',
            field=models.FileField(blank=True, upload_to='backgrounds/', verbose_name='Image de fond'),
        ),
    ]
