# Generated by Django 6.0.4 on 2026-05-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_storesettings_address_storesettings_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nom & prénom du client'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone client'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de vente'),
        ),
    ]
