# Generated by Django 6.0.4 on 2026-05-10 18:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_sale_customer_name_sale_customer_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité perdue')),
                ('loss_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant de la perte (FCFA)')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('reason', models.CharField(choices=[('expired', 'Périmé'), ('damaged', 'Endommagé'), ('stolen', 'Vol'), ('other', 'Autre')], default='expired', max_length=20, verbose_name='Raison')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Perte de stock',
                'verbose_name_plural': 'Pertes de stock',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
