# Generated by Django 6.0.4 on 2026-05-30 22:29

import commande.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0051_alter_storesettings_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=commande.models.generate_client_token, max_length=8, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=commande.models.generate_client_token, max_length=8)),
                ('status', models.CharField(choices=[('pending', '🟡 En attente'), ('preparing', '🔵 En préparation'), ('ready', '✅ Disponible'), ('unavailable', '❌ Indisponible'), ('delivered', '🎉 Livrée'), ('cancelled', '✖️ Annulée')], default='pending', max_length=20)),
                ('pickup_code', models.CharField(default=commande.models.generate_pickup_code, max_length=4, verbose_name='Code retrait')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.CharField(blank=True, max_length=100, verbose_name='Confirmé par')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='commande.orderclient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Produit')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commande.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
    ]
