# Generated by Django 6.0.4 on 2026-06-01 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
        ('store', '0051_alter_storesettings_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_orders', to='store.sale', verbose_name='Vente liée'),
        ),
    ]
