# Generated by Django 6.0.4 on 2026-05-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('subject', models.CharField(max_length=300, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('read', models.BooleanField(default=False, verbose_name='Lu')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10, unique=True, verbose_name='Jour')),
                ('morning', models.CharField(blank=True, default='', max_length=100, verbose_name='Matin')),
                ('afternoon', models.CharField(blank=True, default='', max_length=100, verbose_name='Après-midi')),
                ('closed', models.BooleanField(default=False, verbose_name='Fermé')),
            ],
            options={
                'verbose_name': 'Horaire',
                'verbose_name_plural': 'Horaires',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(choices=[('bi-heart', 'Cœur'), ('bi-people', 'Personnes'), ('bi-cup-hot', 'Repas'), ('bi-book', 'Livre'), ('bi-house-door', 'Maison'), ('bi-church', 'Église'), ('bi-hand-index-thumb', 'Aide'), ('bi-music-note', 'Musique')], default='bi-heart', max_length=50, verbose_name='Icône')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('hero_title', 'Titre hero'), ('hero_subtitle', 'Sous-titre hero'), ('about_title', 'Titre À propos'), ('about_text', 'Texte À propos'), ('services_intro', 'Introduction services'), ('contact_address', 'Adresse'), ('contact_phone', 'Téléphone'), ('contact_email', 'Email')], max_length=50, unique=True, verbose_name='Clé')),
                ('value', models.TextField(verbose_name='Valeur')),
            ],
            options={
                'verbose_name': 'Contenu du site',
                'verbose_name_plural': 'Contenus du site',
            },
        ),
    ]
