# Generated by Django 6.0.4 on 2026-04-28 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_phonecredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCreditPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10, verbose_name='Montant acheté (FCFA)')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Achat de crédits téléphoniques',
                'verbose_name_plural': 'Achats de crédits téléphoniques',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
