# Generated by Django 6.0.4 on 2026-04-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_phonecreditpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Code article'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock minimum'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogramme'), ('l', 'Litre'), ('pièce', 'Pièce'), ('sachet', 'Sachet'), ('boîte', 'Boîte')], default='pièce', max_length=20, verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock'),
        ),
    ]
