# Generated by Django 6.0.4 on 2026-05-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_glaces_boulangerie_categories'),
        ('store', '0015_interface_customization'),
    ]

    operations = [
    ]
