# Generated by Django 6.0.4 on 2026-05-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_sale_options_storesettings_invoice_watermark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='welcome_message',
            field=models.TextField(blank=True, default='', verbose_name='Message de bienvenue'),
        ),
    ]
