# Generated by Django 6.0.4 on 2026-05-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_storesettings_welcome_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Adresse du magasin'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5, verbose_name='Langue'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='signature',
            field=models.FileField(blank=True, upload_to='signatures/', verbose_name='Signature fournisseur'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='voice_alerts',
            field=models.BooleanField(default=False, verbose_name='Alertes vocales stock faible'),
        ),
    ]
