# Generated by Django 6.0.4 on 2026-05-11 13:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_stock_supply_and_carton_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Ouverture')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fermeture')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Fond de caisse (FCFA)')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant réel clôture (FCFA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Client')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Adresse')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='Fournisseur')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Adresse')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='Code-barres'),
        ),
        migrations.AddField(
            model_name='product',
            name='target_margin_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Marge cible (%)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant payé (FCFA)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Payée'), ('partial', 'Paiement partiel'), ('credit', 'Crédit client')], default='paid', max_length=10, verbose_name='Statut paiement'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale_mode',
            field=models.CharField(choices=[('detail', 'Détail'), ('piece', 'Pièce'), ('paquet', 'Paquet'), ('carton', 'Carton'), ('cartouche', 'Cartouche'), ('kg', 'Kg'), ('l', 'L')], default='piece', max_length=10, verbose_name='Mode de vente'),
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'Vente'), ('in', 'Entrée caisse'), ('out', 'Sortie caisse')], default='in', max_length=10, verbose_name='Type')),
                ('label', models.CharField(max_length=180, verbose_name='Libellé')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.sale')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='store.cashsession')),
            ],
            options={
                'verbose_name': 'Mouvement de caisse',
                'verbose_name_plural': 'Mouvements de caisse',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='store.customer'),
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock système')),
                ('counted_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock compté')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Écart')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date inventaire')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustments', to='store.product')),
            ],
            options={
                'verbose_name': 'Ajustement inventaire',
                'verbose_name_plural': 'Ajustements inventaire',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stocksupply',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='store.supplier'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('gerant', 'Gérant'), ('caissier', 'Caissier')], default='caissier', max_length=20, verbose_name='Rôle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateur',
            },
        ),
    ]
