# Generated by Django 6.0.4 on 2026-05-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_cashsession_customer_supplier_product_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='scripture_mode',
            field=models.CharField(choices=[('bible', 'Bible'), ('quran', 'Coran'), ('both', 'Bible et Coran'), ('none', 'Désactivé')], default='bible', max_length=10, verbose_name='Textes spirituels'),
        ),
    ]
