# Generated by Django 6.0.4 on 2026-05-11 20:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_storesettings_scripture_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage (%)'), ('fixed', 'Montant fixe (FCFA)')], default='percentage', max_length=10, verbose_name='Type de remise')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valeur de la remise')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Achat minimum (FCFA)')),
                ('applies_to_all', models.BooleanField(default=False, verbose_name='Appliquer à tous les produits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='store.product', verbose_name='Produits concernés')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('partial', 'Partiellement reçue'), ('received', 'Reçue'), ('cancelled', 'Annulée')], default='draft', max_length=10, verbose_name='Statut')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date de commande')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Date de livraison prévue')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total (FCFA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='store.supplier')),
            ],
            options={
                'verbose_name': 'Bon de commande',
                'verbose_name_plural': 'Bons de commande',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité commandée')),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité reçue')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.purchaseorder')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
    ]
