# Generated by Django 6.0.4 on 2026-05-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_promotion_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('orange_money', 'Orange Money'), ('malitel_momo', 'Malitel MoMo'), ('mixte', 'Mixte')], default='cash', max_length=15, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone mobile money'),
        ),
    ]
