# Generated by Django 6.0.4 on 2026-05-11 22:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_sale_payment_method_sale_payment_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date du retour')),
                ('reason', models.CharField(choices=[('defective', 'Produit défectueux'), ('expired', 'Périmé'), ('wrong', 'Produit erroné'), ('customer_request', 'Demande client'), ('exchange', 'Échange'), ('other', 'Autre')], default='customer_request', max_length=20, verbose_name='Raison')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=10, verbose_name='Statut')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant remboursé (FCFA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='store.sale', verbose_name='Vente')),
            ],
            options={
                'verbose_name': 'Retour / Échange',
                'verbose_name_plural': 'Retours / Échanges',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité retournée')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant remboursé (FCFA)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Produit')),
                ('product_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.productreturn')),
            ],
            options={
                'verbose_name': 'Ligne de retour',
                'verbose_name_plural': 'Lignes de retour',
            },
        ),
    ]
