# Generated by Django 6.0.4 on 2026-05-11 22:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_productreturn_productreturnitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nom client')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date de commande')),
                ('pickup_date', models.DateField(blank=True, null=True, verbose_name='Date de retrait prévue')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('ready', 'Prête'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=10, verbose_name='Statut')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total (FCFA)')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Acompte (FCFA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.customer')),
            ],
            options={
                'verbose_name': 'Commande client',
                'verbose_name_plural': 'Commandes clients',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.customerorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'Ligne de commande client',
                'verbose_name_plural': 'Lignes de commande client',
            },
        ),
    ]
