# Generated by Django 6.0.4 on 2026-05-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_customerorder_customerorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='currency',
            field=models.CharField(choices=[('XOF', 'FCFA (XOF)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dollar (USD)')], default='XOF', max_length=5, verbose_name='Devise par défaut'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='eur_rate',
            field=models.DecimalField(decimal_places=2, default=655.96, max_digits=10, verbose_name='Taux 1 EUR = X FCFA'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='usd_rate',
            field=models.DecimalField(decimal_places=2, default=600.0, max_digits=10, verbose_name='Taux 1 USD = X FCFA'),
        ),
    ]
