# Generated by Django 6.0.4 on 2026-05-12 01:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_storesettings_currency_storesettings_eur_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du compte')),
                ('account_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Numéro de compte')),
                ('bank_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Banque')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Solde (FCFA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compte bancaire',
                'verbose_name_plural': 'Comptes bancaires',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Fidélité', max_length=200, verbose_name='Nom du programme')),
                ('points_per_purchase', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name="Points par 1000 FCFA d'achat")),
                ('points_value', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Valeur de 1 point (FCFA)')),
                ('min_points_to_redeem', models.DecimalField(decimal_places=2, default=100, max_digits=8, verbose_name='Points minimum pour échanger')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Programme de fidélité',
                'verbose_name_plural': 'Programmes de fidélité',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Plafond de crédit (FCFA)'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de vente (EUR)'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de vente (USD)'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='TVA (%)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='sms_api_key',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Clé API SMS'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='sms_from',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Expéditeur SMS'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_api_key',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Clé API WhatsApp'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='ID téléphone WhatsApp'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.bankaccount', verbose_name='Compte bancaire par défaut'),
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Dépôt'), ('withdrawal', 'Retrait'), ('transfer_in', 'Virement reçu'), ('transfer_out', 'Virement émis')], max_length=15, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (FCFA)')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('description', models.CharField(blank=True, default='', max_length=250, verbose_name='Description')),
                ('reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store.bankaccount', verbose_name='Compte')),
            ],
            options={
                'verbose_name': 'Opération bancaire',
                'verbose_name_plural': 'Opérations bancaires',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Points')),
                ('transaction_type', models.CharField(choices=[('earn', 'Gain'), ('burn', 'Échange'), ('bonus', 'Bonus'), ('expired', 'Expiré')], max_length=10, verbose_name='Type')),
                ('description', models.CharField(blank=True, default='', max_length=250, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='store.customer')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.sale')),
            ],
            options={
                'verbose_name': 'Transaction de fidélité',
                'verbose_name_plural': 'Transactions de fidélité',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date du retour')),
                ('reason', models.CharField(choices=[('defective', 'Produit défectueux'), ('expired', 'Périmé'), ('wrong', 'Produit erroné'), ('overstock', 'Surstock'), ('other', 'Autre')], default='defective', max_length=20, verbose_name='Raison')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Retourné au fournisseur'), ('credited', 'Avoir reçu'), ('cancelled', 'Annulé')], default='draft', max_length=10, verbose_name='Statut')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total (FCFA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='store.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Retour fournisseur',
                'verbose_name_plural': 'Retours fournisseurs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité retournée')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat unitaire (FCFA)")),
                ('reason', models.CharField(choices=[('defective', 'Produit défectueux'), ('expired', 'Périmé'), ('wrong', 'Produit erroné'), ('overstock', 'Surstock'), ('other', 'Autre')], default='defective', max_length=20, verbose_name='Raison')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Produit')),
                ('supplier_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.supplierreturn')),
            ],
            options={
                'verbose_name': 'Ligne de retour fournisseur',
                'verbose_name_plural': 'Lignes de retour fournisseur',
            },
        ),
    ]
