# Generated by Django 6.0.4 on 2026-05-12 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_bankaccount_loyaltyprogram_customer_credit_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('client_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone')),
                ('client_address', models.CharField(blank=True, default='', max_length=300, verbose_name='Adresse')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('status', models.CharField(choices=[('devis', 'Devis'), ('confirmé', 'Confirmé'), ('installé', 'Installé'), ('terminé', 'Terminé'), ('annulé', 'Annulé')], default='devis', max_length=10, verbose_name='Statut')),
                ('system_type', models.CharField(choices=[('on_grid', 'On-grid (Raccordé réseau)'), ('off_grid', 'Off-grid (Autonome)'), ('hybrid', 'Hybride')], default='off_grid', max_length=10, verbose_name='Type de système')),
                ('capacity_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Capacité (kWc)')),
                ('panel_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de panneaux')),
                ('battery_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de batteries')),
                ('inverter_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'onduleurs")),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coût total (FCFA)')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix total (FCFA)')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Acompte (FCFA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projet solaire',
                'verbose_name_plural': 'Projets solaires',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
