# Generated by Django 6.0.4 on 2026-05-12 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_solarproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire (FCFA)')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de revient (FCFA)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.solarproject')),
            ],
            options={
                'verbose_name': 'Ligne de devis solaire',
                'verbose_name_plural': 'Lignes de devis solaire',
            },
        ),
    ]
