# Generated by Django 6.0.4 on 2026-05-12 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_solarprojectitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('category', models.CharField(choices=[('panneau', 'Panneau solaire'), ('batterie', 'Batterie'), ('onduleur', 'Onduleur/Convertisseur'), ('structure', 'Structure & Support'), ('cable', 'Câble & Connectique'), ('tableau', 'Tableau électrique'), ('main_oeuvre', "Main-d'œuvre"), ('divers', 'Divers')], default='divers', max_length=50, verbose_name='Catégorie')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix vente (FCFA)')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix revient (FCFA)')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Composant solaire',
                'verbose_name_plural': 'Composants solaires',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='solarproject',
            name='actual_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Gain réel (FCFA)'),
        ),
        migrations.AddField(
            model_name='solarproject',
            name='won_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de réalisation'),
        ),
        migrations.AlterField(
            model_name='solarproject',
            name='status',
            field=models.CharField(choices=[('devis', 'Devis'), ('confirmé', 'Confirmé'), ('installé', 'Installé'), ('terminé', 'Terminé'), ('perdu', 'Marché perdu'), ('annulé', 'Annulé')], default='devis', max_length=10, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='solarprojectitem',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.solarcomponent', verbose_name='Composant'),
        ),
    ]
