# Generated by Django 6.0.4 on 2026-05-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_solarcomponent_solarproject_actual_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='font_family',
            field=models.CharField(choices=[('inter', 'Inter'), ('roboto', 'Roboto'), ('opensans', 'Open Sans'), ('lato', 'Lato'), ('montserrat', 'Montserrat'), ('poppins', 'Poppins'), ('system', 'System UI')], default='inter', max_length=20, verbose_name='Police'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='label_color',
            field=models.CharField(blank=True, default='', help_text='Ex: #1d1d1f. Laisse vide pour utiliser la couleur par défaut.', max_length=7, verbose_name='Couleur des étiquettes'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='primary_color',
            field=models.CharField(blank=True, default='', help_text='Ex: #7f1d1d. Laisse vide pour utiliser la couleur du thème.', max_length=7, verbose_name='Couleur principale'),
        ),
    ]
