# Generated by Django 6.0.4 on 2026-05-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_storesettings_font_family_storesettings_label_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='sms_api_url',
            field=models.CharField(blank=True, default='', help_text='URL du gateway SMS (ex: https://api.africastalking.com/version1/messaging)', max_length=300, verbose_name='URL API SMS'),
        ),
    ]
