# Generated by Django 6.0.4 on 2026-05-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_storesettings_sms_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='auto_backup_enabled',
            field=models.BooleanField(default=False, verbose_name='Sauvegarde automatique'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='auto_backup_interval_days',
            field=models.PositiveIntegerField(default=7, verbose_name='Intervalle (jours)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='last_auto_backup',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière sauvegarde'),
        ),
    ]
