# Generated by Django 6.0.4 on 2026-05-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_storesettings_auto_backup_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default='', max_length=100, verbose_name='Utilisateur')),
                ('action', models.CharField(choices=[('created', 'Création'), ('updated', 'Modification'), ('deleted', 'Suppression'), ('paid', 'Paiement'), ('delivered', 'Livraison'), ('restored', 'Restauration')], max_length=20, verbose_name='Action')),
                ('model_name', models.CharField(max_length=50, verbose_name='Modèle')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objet')),
                ('object_repr', models.CharField(blank=True, default='', max_length=200, verbose_name='Représentation')),
                ('details', models.TextField(blank=True, default='', verbose_name='Détails')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': "Journal d'activité",
                'ordering': ['-created_at'],
            },
        ),
    ]
