# Generated by Django 6.0.4 on 2026-05-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='currency',
            field=models.CharField(choices=[('XOF', 'FCFA'), ('EUR', '€'), ('USD', '$')], default='XOF', max_length=3, verbose_name='Devise'),
        ),
    ]
