# Generated by Django 6.0.4 on 2026-05-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_add_currency_to_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total HT'),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total TVA'),
        ),
    ]
