# Generated by Django 6.0.4 on 2026-05-13 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_add_tva_fields_to_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Solde initial')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Solde restant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Carte cadeau',
                'verbose_name_plural': 'Cartes cadeaux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftCardUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('giftcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='store.giftcard', verbose_name='Carte')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftcard_usages', to='store.sale', verbose_name='Vente')),
            ],
            options={
                'verbose_name': 'Utilisation carte cadeau',
                'verbose_name_plural': 'Utilisations cartes cadeaux',
                'ordering': ['-created_at'],
            },
        ),
    ]
