# Generated by Django 6.0.4 on 2026-05-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_storesettings_label_border_style_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoiffureClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client coiffure',
                'verbose_name_plural': 'Clients coiffure',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.RemoveField(
            model_name='giftcardusage',
            name='giftcard',
        ),
        migrations.RemoveField(
            model_name='giftcardusage',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_ht',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_tva',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='auto_backup_enabled',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='auto_backup_interval_days',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='label_border_style',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='label_color',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='label_columns_print',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='label_columns_screen',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='label_font_size',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='label_layout',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='label_logo',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='label_show_barcode',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='label_show_code',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='label_show_store_name',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='last_auto_backup',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='sms_api_url',
        ),
        migrations.DeleteModel(
            name='GiftCard',
        ),
        migrations.DeleteModel(
            name='GiftCardUsage',
        ),
    ]
