# Generated by Codex on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_coiffureclient_delete_activitylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='label_layout',
            field=models.CharField(choices=[('compact', 'Compacte'), ('detailed', 'Détaillée'), ('minimal', 'Minimale')], default='compact', max_length=20, verbose_name='Disposition étiquettes'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='label_font_size',
            field=models.CharField(choices=[('small', 'Petite'), ('medium', 'Moyenne'), ('large', 'Grande')], default='medium', max_length=10, verbose_name='Taille de police'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='label_border_style',
            field=models.CharField(choices=[('solid', 'Trait plein'), ('dashed', 'Traitillé'), ('dotted', 'Pointillé'), ('none', 'Aucune')], default='dashed', max_length=10, verbose_name='Style de bordure'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='label_columns_screen',
            field=models.PositiveIntegerField(default=2, help_text="Nombre de colonnes sur l'écran (1-6)", verbose_name="Colonnes à l'écran"),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='label_columns_print',
            field=models.PositiveIntegerField(default=4, help_text="Nombre de colonnes à l'impression (2-8)", verbose_name="Colonnes à l'impression"),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='label_logo',
            field=models.FileField(blank=True, help_text='Logo spécifique pour les étiquettes', upload_to='label_logos/', verbose_name='Logo étiquettes'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='label_show_store_name',
            field=models.BooleanField(default=True, verbose_name='Afficher le nom du magasin'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='label_show_barcode',
            field=models.BooleanField(default=True, verbose_name='Afficher le code-barres'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='label_show_code',
            field=models.BooleanField(default=False, verbose_name='Afficher le code produit'),
        ),
    ]
