# Generated by Django 6.0.4 on 2026-05-24 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_purchasepricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('created', 'Création'), ('updated', 'Modification'), ('deleted', 'Suppression'), ('paid', 'Paiement'), ('delivered', 'Livré')], max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Journal activité',
                'verbose_name_plural': "Journal d'activités",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='currency',
            field=models.CharField(default='XOF', max_length=3, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total HT'),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total TVA'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='sms_api_url',
            field=models.CharField(blank=True, default='', help_text='URL du gateway SMS (ex: https://api.africastalking.com/version1/messaging)', max_length=300, verbose_name='URL API SMS'),
        ),
        migrations.AlterField(
            model_name='purchasepricehistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='scripture_mode',
            field=models.CharField(blank=True, choices=[('bible', 'Bible'), ('quran', 'Coran'), ('both', 'Bible et Coran'), ('none', 'Désactivé')], default='bible', max_length=10, verbose_name='Textes spirituels'),
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Solde initial')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Solde restant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Carte cadeau',
                'verbose_name_plural': 'Cartes cadeaux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftCardUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('giftcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='store.giftcard')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sale')),
            ],
            options={
                'verbose_name': 'Utilisation carte cadeau',
                'verbose_name_plural': 'Utilisations cartes cadeaux',
            },
        ),
    ]
