# Generated by Django 6.0.4 on 2026-05-25 23:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_activitylog_sale_currency_sale_total_ht_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('cashier', 'Caissier(ère)'), ('manager', 'Gérant(e)'), ('stock_keeper', 'Magasinier(ère)'), ('sales', 'Vendeur(se)'), ('cleaner', "Agent d'entretien"), ('other', 'Autre')], default='cashier', max_length=20, verbose_name='Poste')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire (FCFA)')),
                ('hire_date', models.DateField(default=datetime.date.today, verbose_name="Date d'embauche")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='is_composite',
            field=models.BooleanField(default=False, verbose_name='Produit composite (recette)'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(auto_now_add=True, verbose_name='Arrivée')),
                ('clock_out', models.DateTimeField(blank=True, null=True, verbose_name='Départ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='store.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-clock_in'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='store.product', verbose_name='Produit composite')),
            ],
            options={
                'verbose_name': 'Recette / Produit composite',
                'verbose_name_plural': 'Recettes / Produits composites',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='store.product', verbose_name='Ingrédient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='store.recipe', verbose_name='Recette')),
            ],
            options={
                'verbose_name': 'Ingrédient de recette',
                'verbose_name_plural': 'Ingrédients des recettes',
            },
        ),
    ]
