# Generated by Django 6.0.4 on 2026-05-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_employee_product_is_composite_attendance_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock minimum (alerte)'),
        ),
    ]
