# Generated by Django 6.0.4 on 2026-05-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_alter_product_min_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='theme',
            field=models.CharField(choices=[('burgundy', 'Rouge bordeaux'), ('blue', 'Bleu moderne'), ('green', 'Vert commerce'), ('dark', 'Sombre'), ('light', 'Clair'), ('cyber', 'Cyber futuriste')], default='burgundy', max_length=20, verbose_name='Thème'),
        ),
    ]
